<?php include 'encabezado.php'; ?>
<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Grupos Solidarios | CEPRODEMIC MULTICREDIT</title>
<meta name="description" content="Conoce la alternativa de Grupos Solidarios de CEPRODEMIC – Multicredit.">
<script src="https://cdn.tailwindcss.com"></script><script>tailwind.config={theme:{extend:{colors:{'brand-green':'#2e9e43','brand-green-dark':'#1c7a30','brand-orange':'#f26e22'}}}};</script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head><body class="bg-gray-50 text-gray-800 overflow-x-hidden"><main class="pt-[88px] md:pt-[96px]">
<section class="bg-gradient-to-br from-[#176b2b] to-[#2e9e43] text-white"><div class="max-w-7xl mx-auto px-4 md:px-10 py-16 md:py-24"><a href="credito-grupal.php" class="inline-flex items-center gap-2 text-green-50 text-sm font-bold mb-7"><i class="fas fa-arrow-left"></i> Volver a Crédito Grupal</a><span class="inline-flex bg-brand-orange px-4 py-2 rounded-full text-xs font-black uppercase tracking-widest">Crédito Grupal</span><h1 class="text-4xl md:text-6xl font-black mt-5">Grupos Solidarios</h1><p class="text-lg md:text-xl text-green-50 mt-4 max-w-3xl leading-relaxed">Una alternativa de financiamiento basada en organización, confianza y responsabilidad compartida.</p></div></section>
<section class="py-14 px-4 md:px-10 bg-white"><div class="max-w-7xl mx-auto grid lg:grid-cols-3 gap-8"><div class="lg:col-span-2"><span class="text-brand-orange text-xs font-black uppercase tracking-widest">Una alternativa grupal</span><h2 class="text-3xl md:text-4xl font-black mt-2">Crecer juntos con responsabilidad</h2><p class="text-gray-600 text-lg leading-relaxed mt-5">Los Grupos Solidarios son una modalidad de crédito grupal que permite organizar a personas con una finalidad común, bajo condiciones y una metodología definidas por la institución.</p><p class="text-gray-500 leading-relaxed mt-4">La conformación del grupo, el monto, plazo, garantías, requisitos y demás condiciones están sujetos a evaluación y a las políticas vigentes.</p></div><div class="rounded-3xl bg-gray-50 border border-gray-200 p-7"><div class="w-14 h-14 rounded-2xl bg-purple-100 text-purple-700 flex items-center justify-center text-2xl"><i class="fas fa-people-group"></i></div><h3 class="text-2xl font-black mt-5">¿Quieres información?</h3><p class="text-gray-600 text-sm mt-3">Conoce si esta modalidad se adapta a tu grupo y a la finalidad del financiamiento.</p><a href="https://wa.me/51968876759?text=Hola%20Multicredit%2C%20deseo%20informaci%C3%B3n%20sobre%20Grupos%20Solidarios." target="_blank" rel="noopener noreferrer" class="mt-6 w-full inline-flex items-center justify-center gap-2 bg-brand-orange text-white px-5 py-3.5 rounded-full font-black"><i class="fab fa-whatsapp text-lg"></i> Hablar con un asesor</a></div></div></section>
<section class="py-14 px-4 md:px-10 bg-gray-50"><div class="max-w-6xl mx-auto"><div class="text-center"><span class="text-brand-green text-xs font-black uppercase tracking-widest">Características</span><h2 class="text-3xl md:text-4xl font-black mt-2">Una metodología que prioriza la organización</h2></div><div class="grid md:grid-cols-3 gap-5 mt-10"><div class="bg-white rounded-3xl p-7 border border-gray-100"><i class="fas fa-user-group text-brand-green text-2xl"></i><h3 class="font-black text-xl mt-4">Integrantes organizados</h3><p class="text-gray-600 text-sm mt-2">Participación coordinada de los integrantes y cumplimiento de los compromisos.</p></div><div class="bg-white rounded-3xl p-7 border border-gray-100"><i class="fas fa-handshake text-brand-orange text-2xl"></i><h3 class="font-black text-xl mt-4">Responsabilidad solidaria</h3><p class="text-gray-600 text-sm mt-2">El funcionamiento del grupo considera las responsabilidades establecidas en la modalidad.</p></div><div class="bg-white rounded-3xl p-7 border border-gray-100"><i class="fas fa-chart-line text-brand-green text-2xl"></i><h3 class="font-black text-xl mt-4">Finalidad productiva</h3><p class="text-gray-600 text-sm mt-2">Puede orientarse al fortalecimiento de actividades económicas, según evaluación.</p></div></div></div></section>
<section class="py-14 px-4 md:px-10 bg-white"><div class="max-w-5xl mx-auto"><div class="text-center"><span class="text-brand-orange text-xs font-black uppercase tracking-widest">Proceso referencial</span><h2 class="text-3xl md:text-4xl font-black mt-2">¿Cómo empezar?</h2></div><div class="grid md:grid-cols-4 gap-5 mt-10"><div class="text-center"><div class="mx-auto w-12 h-12 rounded-full bg-green-50 text-brand-green font-black flex items-center justify-center">01</div><h3 class="font-black mt-4">Forma tu grupo</h3><p class="text-sm text-gray-500 mt-1">Organiza a los participantes interesados.</p></div><div class="text-center"><div class="mx-auto w-12 h-12 rounded-full bg-green-50 text-brand-green font-black flex items-center justify-center">02</div><h3 class="font-black mt-4">Consulta</h3><p class="text-sm text-gray-500 mt-1">Conoce requisitos y condiciones.</p></div><div class="text-center"><div class="mx-auto w-12 h-12 rounded-full bg-green-50 text-brand-green font-black flex items-center justify-center">03</div><h3 class="font-black mt-4">Evaluación</h3><p class="text-sm text-gray-500 mt-1">Se revisa la solicitud y el grupo.</p></div><div class="text-center"><div class="mx-auto w-12 h-12 rounded-full bg-green-50 text-brand-green font-black flex items-center justify-center">04</div><h3 class="font-black mt-4">Respuesta</h3><p class="text-sm text-gray-500 mt-1">Se informa el resultado y condiciones.</p></div></div></div></section>
<section class="px-4 md:px-10 pb-14"><div class="max-w-7xl mx-auto rounded-3xl bg-gradient-to-r from-[#176b2b] to-[#2e9e43] text-white p-8 md:p-12 flex flex-col md:flex-row items-center justify-between gap-6"><div><span class="text-green-100 text-xs font-black uppercase tracking-widest">CEPRODEMIC – Multicredit</span><h2 class="text-3xl font-black mt-2">¿Tu grupo necesita financiamiento?</h2><p class="text-green-50 mt-2">Habla con un asesor para conocer esta alternativa.</p></div><a href="https://wa.me/51968876759?text=Hola%20Multicredit%2C%20mi%20grupo%20desea%20informaci%C3%B3n%20sobre%20Grupos%20Solidarios." target="_blank" rel="noopener noreferrer" class="bg-brand-orange px-7 py-4 rounded-full font-black inline-flex items-center gap-2"><i class="fab fa-whatsapp text-xl"></i> Solicitar información</a></div></section>
</main><?php include 'footer.php'; ?></body></html>
