<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Grupos Solidarios | CEPRODEMIC MULTICREDIT</title>
<meta name="description" content="Conoce Grupos Solidarios de CEPRODEMIC – Multicredit: tasa mensual de 3.6 %, plazo de 6 a 12 meses y pagos mensuales.">
<script src="https://cdn.tailwindcss.com"></script><script>tailwind.config={theme:{extend:{colors:{'brand-green':'#2e9e43','brand-green-dark':'#1c7a30','brand-orange':'#f26e22'}}}};</script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&family=Poppins:wght@500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="css/mc-productos-ultra.css">
    <style>
        .mc-credit-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));margin-top:2rem;background:#fff!important;color:#12301f!important;border:1px solid rgba(13,92,46,.14);border-radius:24px;box-shadow:0 18px 55px rgba(0,0,0,.14);overflow:hidden}
        .mc-credit-summary-item{padding:1.6rem 1rem;text-align:center}
        .mc-credit-summary-item+.mc-credit-summary-item{border-left:1px solid #e5e7eb}
        .mc-credit-summary-label{display:block;color:#607067!important;font-size:.78rem;font-weight:800;text-transform:uppercase;letter-spacing:.08em}
        .mc-credit-summary-value{display:block;color:var(--mc-accent)!important;font-family:'Poppins','Inter',sans-serif;font-size:clamp(1.35rem,2.5vw,2rem);font-weight:900;line-height:1.2;margin-top:.45rem}
        .mc-benefit-layout{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1.25rem;margin-top:2rem}
        .mc-benefit-panel{background:#fff!important;color:#12301f!important;border:1px solid rgba(13,92,46,.14);border-radius:24px;padding:2rem;box-shadow:0 16px 45px rgba(3,29,14,.10)}
        .mc-benefit-panel i{color:var(--mc-accent)!important;font-size:1.7rem}
        .mc-benefit-panel h3{color:#12301f!important;font-size:1.25rem;font-weight:900;margin-top:1rem}
        .mc-benefit-panel p{color:#526158!important;font-size:.95rem;line-height:1.7!important;margin-top:.55rem}
        .mc-credit-summary,.mc-credit-summary *,.mc-benefit-layout,.mc-benefit-layout *,body[data-product="solidarios"] .mc-reveal{opacity:1!important;visibility:visible!important;transform:none!important;filter:none!important}
        @media(max-width:767px){.mc-credit-summary{grid-template-columns:1fr}.mc-credit-summary-item+.mc-credit-summary-item{border-left:0;border-top:1px solid #e5e7eb}.mc-benefit-layout{grid-template-columns:1fr}}
    </style>
</head><body class="bg-gray-50 text-gray-800 overflow-x-hidden mc-ultra-page" data-product="solidarios">
<?php include 'encabezado.php'; ?>
<main class="pt-[88px] md:pt-[96px]">
<section class="bg-gradient-to-br from-[#176b2b] to-[#2e9e43] text-white"><div class="max-w-7xl mx-auto px-4 md:px-10 py-16 md:py-24"><a href="credito-grupal.php" class="inline-flex items-center gap-2 text-green-50 text-sm font-bold mb-7"><i class="fas fa-arrow-left"></i> Volver a Crédito Grupal</a><span class="inline-flex bg-brand-orange px-4 py-2 rounded-full text-xs font-black uppercase tracking-widest">Crédito Grupal</span><h1 class="text-4xl md:text-6xl font-black mt-5">Grupos Solidarios</h1><p class="text-lg md:text-xl text-green-50 mt-4 max-w-3xl leading-relaxed">Una alternativa de financiamiento basada en organización, confianza y responsabilidad compartida.</p></div></section>
<section class="py-14 px-4 md:px-10 bg-white"><div class="max-w-7xl mx-auto grid lg:grid-cols-3 gap-8"><div class="lg:col-span-2"><span class="text-brand-orange text-xs font-black uppercase tracking-widest">Una alternativa grupal</span><h2 class="text-3xl md:text-4xl font-black mt-2">Crecer juntos con responsabilidad</h2><p class="text-gray-600 text-lg leading-relaxed mt-5">Los Grupos Solidarios son una modalidad de crédito grupal que permite organizar a personas con una finalidad común, bajo condiciones y una metodología definidas por la institución.</p><p class="text-gray-500 leading-relaxed mt-4">La conformación del grupo, el monto, las garantías, los requisitos y las demás condiciones están sujetos a evaluación y a las políticas vigentes.</p></div><div class="rounded-3xl bg-gray-50 border border-gray-200 p-7"><div class="w-14 h-14 rounded-2xl bg-purple-100 text-purple-700 flex items-center justify-center text-2xl"><i class="fas fa-people-group"></i></div><h3 class="text-2xl font-black mt-5">¿Quieres información?</h3><p class="text-gray-600 text-sm mt-3">Conoce si esta modalidad se adapta a tu grupo y a la finalidad del financiamiento.</p><a href="https://wa.me/51968782473?text=Hola%20Multicredit%2C%20deseo%20informaci%C3%B3n%20sobre%20Grupos%20Solidarios." target="_blank" rel="noopener noreferrer" class="mt-6 w-full inline-flex items-center justify-center gap-2 bg-brand-orange text-white px-5 py-3.5 rounded-full font-black"><i class="fab fa-whatsapp text-lg"></i> Hablar con un asesor</a></div></div></section>
<section class="py-12 px-4 md:px-10 bg-gray-50"><div class="max-w-5xl mx-auto"><div class="text-center max-w-3xl mx-auto"><span class="text-brand-orange text-xs font-black uppercase tracking-widest">Condiciones principales</span><h2 class="text-3xl md:text-4xl font-black mt-2">Grupos Solidarios</h2><p class="text-gray-600 mt-3">Información financiera presentada en una sola ficha, clara y fácil de consultar.</p></div><div class="mc-credit-summary mc-visible" aria-label="Condiciones de Grupos Solidarios"><div class="mc-credit-summary-item"><span class="mc-credit-summary-label">Tasa mensual</span><strong class="mc-credit-summary-value">3.6 %</strong></div><div class="mc-credit-summary-item"><span class="mc-credit-summary-label">Plazo</span><strong class="mc-credit-summary-value">6 a 12 meses</strong></div><div class="mc-credit-summary-item"><span class="mc-credit-summary-label">Frecuencia de pago</span><strong class="mc-credit-summary-value">Mensual</strong></div></div><p class="text-center text-xs text-gray-500 mt-5">El monto, la aprobación y las demás condiciones están sujetos a evaluación crediticia y a las políticas vigentes de Multicredit.</p></div></section>
<section class="py-14 px-4 md:px-10 bg-gray-50"><div class="max-w-6xl mx-auto"><div class="text-center max-w-3xl mx-auto"><span class="text-brand-green text-xs font-black uppercase tracking-widest">Características</span><h2 class="text-3xl md:text-4xl font-black mt-2">Una metodología basada en la confianza</h2></div><div class="mc-benefit-layout mc-visible"><div class="mc-benefit-panel"><i class="fas fa-handshake"></i><h3>Organización y responsabilidad compartida</h3><p>Los integrantes participan de manera coordinada y asumen los compromisos establecidos para el funcionamiento del grupo.</p></div><div class="mc-benefit-panel"><i class="fas fa-chart-line"></i><h3>Financiamiento con finalidad productiva</h3><p>Puede orientarse al fortalecimiento de pequeños negocios y actividades económicas, de acuerdo con la evaluación.</p></div></div></div></section>
<section class="py-14 px-4 md:px-10 bg-white"><div class="max-w-5xl mx-auto"><div class="text-center"><span class="text-brand-orange text-xs font-black uppercase tracking-widest">Proceso referencial</span><h2 class="text-3xl md:text-4xl font-black mt-2">¿Cómo empezar?</h2></div><div class="grid md:grid-cols-4 gap-5 mt-10"><div class="text-center"><div class="mx-auto w-12 h-12 rounded-full bg-green-50 text-brand-green font-black flex items-center justify-center">01</div><h3 class="font-black mt-4">Forma tu grupo</h3><p class="text-sm text-gray-500 mt-1">Organiza a los participantes interesados.</p></div><div class="text-center"><div class="mx-auto w-12 h-12 rounded-full bg-green-50 text-brand-green font-black flex items-center justify-center">02</div><h3 class="font-black mt-4">Consulta</h3><p class="text-sm text-gray-500 mt-1">Conoce requisitos y condiciones.</p></div><div class="text-center"><div class="mx-auto w-12 h-12 rounded-full bg-green-50 text-brand-green font-black flex items-center justify-center">03</div><h3 class="font-black mt-4">Evaluación</h3><p class="text-sm text-gray-500 mt-1">Se revisa la solicitud y el grupo.</p></div><div class="text-center"><div class="mx-auto w-12 h-12 rounded-full bg-green-50 text-brand-green font-black flex items-center justify-center">04</div><h3 class="font-black mt-4">Respuesta</h3><p class="text-sm text-gray-500 mt-1">Se informa el resultado y condiciones.</p></div></div></div></section>
<section class="px-4 md:px-10 pb-14"><div class="max-w-7xl mx-auto rounded-3xl bg-gradient-to-r from-[#176b2b] to-[#2e9e43] text-white p-8 md:p-12 flex flex-col md:flex-row items-center justify-between gap-6"><div><span class="text-green-100 text-xs font-black uppercase tracking-widest">CEPRODEMIC – Multicredit</span><h2 class="text-3xl font-black mt-2">¿Tu grupo necesita financiamiento?</h2><p class="text-green-50 mt-2">Habla con un asesor para conocer esta alternativa.</p></div><a href="https://wa.me/51968782473?text=Hola%20Multicredit%2C%20mi%20grupo%20desea%20informaci%C3%B3n%20sobre%20Grupos%20Solidarios." target="_blank" rel="noopener noreferrer" class="bg-brand-orange px-7 py-4 rounded-full font-black inline-flex items-center gap-2"><i class="fab fa-whatsapp text-xl"></i> Solicitar información</a></div></section>
</main><?php include 'footer.php'; ?>
<script src="js/mc-productos-ultra.js" defer></script>
</body></html>
